version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "db"
    restart: always
    ports:
    - 5432:5432
    # volumes:
    # - data:/var/lib/postgresql/data
    environment:
    - POSTGRES_PASSWORD=AAAaaa123!@#
    - POSTGRES_USER=postgres
    - POSTGRES_DB=todo_db
  app:
    build:
      context: ./todo-service
      dockerfile: Dockerfile
    ports:
    - 8080:8080
    depends_on:
    - db
# volumes:
  # data: