version: "3"
services:
  todo_postgres:
    image: "postgres:11"
    container_name: "db"
    restart: always
    ports:
    - 5432:5432
    # volumes:
    # - data:/var/lib/postgresql/data
    environment:
    - POSTGRES_PASSWORD=AAAaaa123!@#
    - POSTGRES_USER=postgres
    - POSTGRES_DB=todo_db
  todo_app:
    build:
      context: ./todo-service
      dockerfile: Dockerfile
    ports:
    - 8080:8080
    depends_on:
    - todo_postgres
    environment:
    - spring.datasource.url=jdbc:postgresql://todo_postgres:5432/todo_db
    - spring.datasource.username=postgres
    - spring.datasource.password=AAAaaa123!@#
# volumes:
  # data: